// const produce = [
//   "egg",
//   "garlic",
//   "chicken breast",
//   "beef steak",
//   "feta",
//   "cream cheese",
//   "strawberry",
//   "cherry",
//   "blueberry",
// ];

const produceWithMeta = [
  {
    OID_: 0,
    ProduceDir: 1,
    Farm_Key: "BLC001",
    Produce_Type: "bell pepper",
    season: "summer,fall",
    X: -105.1682183,
    Y: 40.18876728,
    Farm_Name: "Aspen Moon Farm",
    Full_Addre: "7929 Hygiene Rd., Longmont",
    Email: "info@aspenmoonfarm.com",
    Website: "www.aspenmoonfarm.com",
  },
  {
    OID_: 1,
    ProduceDir: 2,
    Farm_Key: "BLC001",
    Produce_Type: "beetroot",
    season: "summer,fall,winter",
    X: -105.1682183,
    Y: 40.18876728,
    Farm_Name: "Aspen Moon Farm",
    Full_Addre: "7929 Hygiene Rd., Longmont",
    Email: "info@aspenmoonfarm.com",
    Website: "www.aspenmoonfarm.com",
  },
  {
    OID_: 2,
    ProduceDir: 3,
    Farm_Key: "BLC001",
    Produce_Type: "cabbage",
    season: "spring,fall,winter",
    X: -105.1682183,
    Y: 40.18876728,
    Farm_Name: "Aspen Moon Farm",
    Full_Addre: "7929 Hygiene Rd., Longmont",
    Email: "info@aspenmoonfarm.com",
    Website: "www.aspenmoonfarm.com",
  },
  {
    OID_: 3,
    ProduceDir: 4,
    Farm_Key: "BLC001",
    Produce_Type: "broccoli",
    season: "spring,fall",
    X: -105.1682183,
    Y: 40.18876728,
    Farm_Name: "Aspen Moon Farm",
    Full_Addre: "7929 Hygiene Rd., Longmont",
    Email: "info@aspenmoonfarm.com",
    Website: "www.aspenmoonfarm.com",
  },
  {
    OID_: 4,
    ProduceDir: 5,
    Farm_Key: "BLC001",
    Produce_Type: "carrot",
    season: "spring,summer,fall,winter",
    X: -105.1682183,
    Y: 40.18876728,
    Farm_Name: "Aspen Moon Farm",
    Full_Addre: "7929 Hygiene Rd., Longmont",
    Email: "info@aspenmoonfarm.com",
    Website: "www.aspenmoonfarm.com",
  },
  {
    OID_: 5,
    ProduceDir: 6,
    Farm_Key: "BLC001",
    Produce_Type: "cauliflower",
    season: "fall",
    X: -105.1682183,
    Y: 40.18876728,
    Farm_Name: "Aspen Moon Farm",
    Full_Addre: "7929 Hygiene Rd., Longmont",
    Email: "info@aspenmoonfarm.com",
    Website: "www.aspenmoonfarm.com",
  },
  {
    OID_: 6,
    ProduceDir: 7,
    Farm_Key: "BLC001",
    Produce_Type: "celery",
    season: "spring,summer,fall,winter",
    X: -105.1682183,
    Y: 40.18876728,
    Farm_Name: "Aspen Moon Farm",
    Full_Addre: "7929 Hygiene Rd., Longmont",
    Email: "info@aspenmoonfarm.com",
    Website: "www.aspenmoonfarm.com",
  },
  {
    OID_: 7,
    ProduceDir: 8,
    Farm_Key: "BLC001",
    Produce_Type: "celeriac",
    season: "spring,summer,fall,winter",
    X: -105.1682183,
    Y: 40.18876728,
    Farm_Name: "Aspen Moon Farm",
    Full_Addre: "7929 Hygiene Rd., Longmont",
    Email: "info@aspenmoonfarm.com",
    Website: "www.aspenmoonfarm.com",
  },
  {
    OID_: 8,
    ProduceDir: 9,
    Farm_Key: "BLC001",
    Produce_Type: "chile pepper",
    season: "summer,fall",
    X: -105.1682183,
    Y: 40.18876728,
    Farm_Name: "Aspen Moon Farm",
    Full_Addre: "7929 Hygiene Rd., Longmont",
    Email: "info@aspenmoonfarm.com",
    Website: "www.aspenmoonfarm.com",
  },
  {
    OID_: 9,
    ProduceDir: 10,
    Farm_Key: "BLC001",
    Produce_Type: "cucumber",
    season: "summer",
    X: -105.1682183,
    Y: 40.18876728,
    Farm_Name: "Aspen Moon Farm",
    Full_Addre: "7929 Hygiene Rd., Longmont",
    Email: "info@aspenmoonfarm.com",
    Website: "www.aspenmoonfarm.com",
  },
  {
    OID_: 10,
    ProduceDir: 11,
    Farm_Key: "BLC001",
    Produce_Type: "cornmeal",
    season: "spring,summer,fall,winter",
    X: -105.1682183,
    Y: 40.18876728,
    Farm_Name: "Aspen Moon Farm",
    Full_Addre: "7929 Hygiene Rd., Longmont",
    Email: "info@aspenmoonfarm.com",
    Website: "www.aspenmoonfarm.com",
  },
  {
    OID_: 11,
    ProduceDir: 12,
    Farm_Key: "BLC001",
    Produce_Type: "mixed greens",
    season: "spring,fall",
    X: -105.1682183,
    Y: 40.18876728,
    Farm_Name: "Aspen Moon Farm",
    Full_Addre: "7929 Hygiene Rd., Longmont",
    Email: "info@aspenmoonfarm.com",
    Website: "www.aspenmoonfarm.com",
  },
  {
    OID_: 12,
    ProduceDir: 13,
    Farm_Key: "BLC001",
    Produce_Type: "garlic",
    season: "spring,summer,fall",
    X: -105.1682183,
    Y: 40.18876728,
    Farm_Name: "Aspen Moon Farm",
    Full_Addre: "7929 Hygiene Rd., Longmont",
    Email: "info@aspenmoonfarm.com",
    Website: "www.aspenmoonfarm.com",
  },
  {
    OID_: 13,
    ProduceDir: 14,
    Farm_Key: "BLC001",
    Produce_Type: "eggplant",
    season: "summer",
    X: -105.1682183,
    Y: 40.18876728,
    Farm_Name: "Aspen Moon Farm",
    Full_Addre: "7929 Hygiene Rd., Longmont",
    Email: "info@aspenmoonfarm.com",
    Website: "www.aspenmoonfarm.com",
  },
  {
    OID_: 14,
    ProduceDir: 15,
    Farm_Key: "BLC001",
    Produce_Type: "kohlrabi",
    season: "winter",
    X: -105.1682183,
    Y: 40.18876728,
    Farm_Name: "Aspen Moon Farm",
    Full_Addre: "7929 Hygiene Rd., Longmont",
    Email: "info@aspenmoonfarm.com",
    Website: "www.aspenmoonfarm.com",
  },
  {
    OID_: 15,
    ProduceDir: 16,
    Farm_Key: "BLC001",
    Produce_Type: "egg",
    season: "spring,summer,fall,winter",
    X: -105.1682183,
    Y: 40.18876728,
    Farm_Name: "Aspen Moon Farm",
    Full_Addre: "7929 Hygiene Rd., Longmont",
    Email: "info@aspenmoonfarm.com",
    Website: "www.aspenmoonfarm.com",
  },
  {
    OID_: 16,
    ProduceDir: 17,
    Farm_Key: "BLC001",
    Produce_Type: "leek",
    season: "winter",
    X: -105.1682183,
    Y: 40.18876728,
    Farm_Name: "Aspen Moon Farm",
    Full_Addre: "7929 Hygiene Rd., Longmont",
    Email: "info@aspenmoonfarm.com",
    Website: "www.aspenmoonfarm.com",
  },
  {
    OID_: 17,
    ProduceDir: 18,
    Farm_Key: "BLC001",
    Produce_Type: "onion",
    season: "spring,fall,winter",
    X: -105.1682183,
    Y: 40.18876728,
    Farm_Name: "Aspen Moon Farm",
    Full_Addre: "7929 Hygiene Rd., Longmont",
    Email: "info@aspenmoonfarm.com",
    Website: "www.aspenmoonfarm.com",
  },
  {
    OID_: 18,
    ProduceDir: 19,
    Farm_Key: "BLC001",
    Produce_Type: "potato",
    season: "fall,winter",
    X: -105.1682183,
    Y: 40.18876728,
    Farm_Name: "Aspen Moon Farm",
    Full_Addre: "7929 Hygiene Rd., Longmont",
    Email: "info@aspenmoonfarm.com",
    Website: "www.aspenmoonfarm.com",
  },
  {
    OID_: 19,
    ProduceDir: 20,
    Farm_Key: "BLC001",
    Produce_Type: "lettuce",
    season: "spring,fall",
    X: -105.1682183,
    Y: 40.18876728,
    Farm_Name: "Aspen Moon Farm",
    Full_Addre: "7929 Hygiene Rd., Longmont",
    Email: "info@aspenmoonfarm.com",
    Website: "www.aspenmoonfarm.com",
  },
  {
    OID_: 20,
    ProduceDir: 21,
    Farm_Key: "BLC001",
    Produce_Type: "raspberry",
    season: "summer,fall",
    X: -105.1682183,
    Y: 40.18876728,
    Farm_Name: "Aspen Moon Farm",
    Full_Addre: "7929 Hygiene Rd., Longmont",
    Email: "info@aspenmoonfarm.com",
    Website: "www.aspenmoonfarm.com",
  },
  {
    OID_: 21,
    ProduceDir: 22,
    Farm_Key: "BLC001",
    Produce_Type: "radish",
    season: "spring,fall",
    X: -105.1682183,
    Y: 40.18876728,
    Farm_Name: "Aspen Moon Farm",
    Full_Addre: "7929 Hygiene Rd., Longmont",
    Email: "info@aspenmoonfarm.com",
    Website: "www.aspenmoonfarm.com",
  },
  {
    OID_: 22,
    ProduceDir: 23,
    Farm_Key: "BLC001",
    Produce_Type: "rhubarb",
    season: "spring",
    X: -105.1682183,
    Y: 40.18876728,
    Farm_Name: "Aspen Moon Farm",
    Full_Addre: "7929 Hygiene Rd., Longmont",
    Email: "info@aspenmoonfarm.com",
    Website: "www.aspenmoonfarm.com",
  },
  {
    OID_: 23,
    ProduceDir: 24,
    Farm_Key: "BLC001",
    Produce_Type: "pumpkin",
    season: "fall,winter",
    X: -105.1682183,
    Y: 40.18876728,
    Farm_Name: "Aspen Moon Farm",
    Full_Addre: "7929 Hygiene Rd., Longmont",
    Email: "info@aspenmoonfarm.com",
    Website: "www.aspenmoonfarm.com",
  },
  {
    OID_: 24,
    ProduceDir: 25,
    Farm_Key: "BLC001",
    Produce_Type: "tomato",
    season: "summer",
    X: -105.1682183,
    Y: 40.18876728,
    Farm_Name: "Aspen Moon Farm",
    Full_Addre: "7929 Hygiene Rd., Longmont",
    Email: "info@aspenmoonfarm.com",
    Website: "www.aspenmoonfarm.com",
  },
  {
    OID_: 25,
    ProduceDir: 26,
    Farm_Key: "BLC001",
    Produce_Type: "spinach",
    season: "spring,fall",
    X: -105.1682183,
    Y: 40.18876728,
    Farm_Name: "Aspen Moon Farm",
    Full_Addre: "7929 Hygiene Rd., Longmont",
    Email: "info@aspenmoonfarm.com",
    Website: "www.aspenmoonfarm.com",
  },
  {
    OID_: 26,
    ProduceDir: 27,
    Farm_Key: "BLC001",
    Produce_Type: "sweet corn",
    season: "summer",
    X: -105.1682183,
    Y: 40.18876728,
    Farm_Name: "Aspen Moon Farm",
    Full_Addre: "7929 Hygiene Rd., Longmont",
    Email: "info@aspenmoonfarm.com",
    Website: "www.aspenmoonfarm.com",
  },
  {
    OID_: 27,
    ProduceDir: 28,
    Farm_Key: "BLC001",
    Produce_Type: "summer squash",
    season: "summer",
    X: -105.1682183,
    Y: 40.18876728,
    Farm_Name: "Aspen Moon Farm",
    Full_Addre: "7929 Hygiene Rd., Longmont",
    Email: "info@aspenmoonfarm.com",
    Website: "www.aspenmoonfarm.com",
  },
  {
    OID_: 28,
    ProduceDir: 29,
    Farm_Key: "BLC001",
    Produce_Type: "turnip",
    season: "spring,fall,winter",
    X: -105.1682183,
    Y: 40.18876728,
    Farm_Name: "Aspen Moon Farm",
    Full_Addre: "7929 Hygiene Rd., Longmont",
    Email: "info@aspenmoonfarm.com",
    Website: "www.aspenmoonfarm.com",
  },
  {
    OID_: 29,
    ProduceDir: 30,
    Farm_Key: "BLC001",
    Produce_Type: "zucchini",
    season: "summer",
    X: -105.1682183,
    Y: 40.18876728,
    Farm_Name: "Aspen Moon Farm",
    Full_Addre: "7929 Hygiene Rd., Longmont",
    Email: "info@aspenmoonfarm.com",
    Website: "www.aspenmoonfarm.com",
  },
  {
    OID_: 30,
    ProduceDir: 31,
    Farm_Key: "BLC003",
    Produce_Type: "cornmeal",
    season: "spring,summer,fall,winter",
    X: -105.2422634,
    Y: 40.05111656,
    Farm_Name: "Colorado’s Best Beef Company",
    Full_Addre: "4791 Jay Rd. Boulder",
    Email: "info@cobestbeef.com",
    Website: "www.naturalbeef.com",
  },
  {
    OID_: 31,
    ProduceDir: 32,
    Farm_Key: "BLC002",
    Produce_Type: "popcorn",
    season: "spring,summer,fall,winter",
    X: -105.404544,
    Y: 39.97885998,
    Farm_Name: "B Bar S Ranch Grass-Fed Beef",
    Full_Addre: "282 Twin Sisters Rd., Nederland, CO 80466",
    Email: "moreinfo@bbarsranch.com",
    Website: "www.bbarsranch.com",
  },
  {
    OID_: 32,
    ProduceDir: 33,
    Farm_Key: "BLC004",
    Produce_Type: "green beans",
    season: "summer,fall",
    X: -105.105036,
    Y: 40.03208201,
    Farm_Name: "Cottonwood Farm LLC",
    Full_Addre: "10600 Isabelle Rd. Lafayette, CO 80026",
    Email: "bob@cottonwoodfarms.com",
    Website: "www.cottonwoodfarms.com",
  },
  {
    OID_: 33,
    ProduceDir: 34,
    Farm_Key: "BLC004",
    Produce_Type: "ground beef",
    season: "spring,summer,fall,winter",
    X: -105.105036,
    Y: 40.03208201,
    Farm_Name: "Cottonwood Farm LLC",
    Full_Addre: "10600 Isabelle Rd. Lafayette, CO 80026",
    Email: "bob@cottonwoodfarms.com",
    Website: "www.cottonwoodfarms.com",
  },
  {
    OID_: 34,
    ProduceDir: 35,
    Farm_Key: "BLC006",
    Produce_Type: "jam",
    season: "spring,summer,fall,winter",
    X: -105.2762833,
    Y: 40.03482968,
    Farm_Name: "Growing Gardens",
    Full_Addre: "1630 Hawthorn Ave. Boulder, CO 80304",
    Email: "info@growinggardens.org",
    Website: "www.growinggardens.org",
  },
  {
    OID_: 35,
    ProduceDir: 36,
    Farm_Key: "BLC004",
    Produce_Type: "pumpkin",
    season: "fall,winter",
    X: -105.105036,
    Y: 40.03208201,
    Farm_Name: "Cottonwood Farm LLC",
    Full_Addre: "10600 Isabelle Rd. Lafayette, CO 80026",
    Email: "bob@cottonwoodfarms.com",
    Website: "www.cottonwoodfarms.com",
  },
  {
    OID_: 36,
    ProduceDir: 37,
    Farm_Key: "BLC004",
    Produce_Type: "butternut squash",
    season: "fall,winter",
    X: -105.105036,
    Y: 40.03208201,
    Farm_Name: "Cottonwood Farm LLC",
    Full_Addre: "10600 Isabelle Rd. Lafayette, CO 80026",
    Email: "bob@cottonwoodfarms.com",
    Website: "www.cottonwoodfarms.com",
  },
  {
    OID_: 37,
    ProduceDir: 38,
    Farm_Key: "BLC006",
    Produce_Type: "dried fruit",
    season: "spring,summer,fall,winter",
    X: -105.2762833,
    Y: 40.03482968,
    Farm_Name: "Growing Gardens",
    Full_Addre: "1630 Hawthorn Ave. Boulder, CO 80304",
    Email: "info@growinggardens.org",
    Website: "www.growinggardens.org",
  },
  {
    OID_: 38,
    ProduceDir: 39,
    Farm_Key: "BLC006",
    Produce_Type: "applesauce",
    season: "spring,summer,fall,winter",
    X: -105.2762833,
    Y: 40.03482968,
    Farm_Name: "Growing Gardens",
    Full_Addre: "1630 Hawthorn Ave. Boulder, CO 80304",
    Email: "info@growinggardens.org",
    Website: "www.growinggardens.org",
  },
  {
    OID_: 39,
    ProduceDir: 40,
    Farm_Key: "BLC004",
    Produce_Type: "cider",
    season: "spring,summer,fall,winter",
    X: -105.105036,
    Y: 40.03208201,
    Farm_Name: "Cottonwood Farm LLC",
    Full_Addre: "10600 Isabelle Rd. Lafayette, CO 80026",
    Email: "bob@cottonwoodfarms.com",
    Website: "www.cottonwoodfarms.com",
  },
  {
    OID_: 40,
    ProduceDir: 41,
    Farm_Key: "BLC006",
    Produce_Type: "mixed vegetable",
    season: "spring,summer,fall,winter",
    X: -105.2762833,
    Y: 40.03482968,
    Farm_Name: "Growing Gardens",
    Full_Addre: "1630 Hawthorn Ave. Boulder, CO 80304",
    Email: "info@growinggardens.org",
    Website: "www.growinggardens.org",
  },
  {
    OID_: 41,
    ProduceDir: 42,
    Farm_Key: "BLC006",
    Produce_Type: "cider",
    season: "spring,summer,fall,winter",
    X: -105.2762833,
    Y: 40.03482968,
    Farm_Name: "Growing Gardens",
    Full_Addre: "1630 Hawthorn Ave. Boulder, CO 80304",
    Email: "info@growinggardens.org",
    Website: "www.growinggardens.org",
  },
  {
    OID_: 42,
    ProduceDir: 43,
    Farm_Key: "BLC006",
    Produce_Type: "tomato",
    season: "summer",
    X: -105.2762833,
    Y: 40.03482968,
    Farm_Name: "Growing Gardens",
    Full_Addre: "1630 Hawthorn Ave. Boulder, CO 80304",
    Email: "info@growinggardens.org",
    Website: "www.growinggardens.org",
  },
  {
    OID_: 43,
    ProduceDir: 44,
    Farm_Key: "BLC006",
    Produce_Type: "mixed herbs",
    season: "spring,summer,fall,winter",
    X: -105.2762833,
    Y: 40.03482968,
    Farm_Name: "Growing Gardens",
    Full_Addre: "1630 Hawthorn Ave. Boulder, CO 80304",
    Email: "info@growinggardens.org",
    Website: "www.growinggardens.org",
  },
  {
    OID_: 44,
    ProduceDir: 45,
    Farm_Key: "BLC007",
    Produce_Type: "bell pepper",
    season: "summer,fall",
    X: -105.1638278,
    Y: 40.11611101,
    Farm_Name: "Kilt Farm",
    Full_Addre: "8140 Oxford Rd. Niwot",
    Email: "michael@kiltfarm.com",
    Website: "www.kiltfarm.com",
  },
  {
    OID_: 45,
    ProduceDir: 46,
    Farm_Key: "BLC007",
    Produce_Type: "beetroot",
    season: "summer,fall,winter",
    X: -105.1638278,
    Y: 40.11611101,
    Farm_Name: "Kilt Farm",
    Full_Addre: "8140 Oxford Rd. Niwot",
    Email: "michael@kiltfarm.com",
    Website: "www.kiltfarm.com",
  },
  {
    OID_: 46,
    ProduceDir: 47,
    Farm_Key: "BLC007",
    Produce_Type: "cabbage",
    season: "spring,fall,winter",
    X: -105.1638278,
    Y: 40.11611101,
    Farm_Name: "Kilt Farm",
    Full_Addre: "8140 Oxford Rd. Niwot",
    Email: "michael@kiltfarm.com",
    Website: "www.kiltfarm.com",
  },
  {
    OID_: 47,
    ProduceDir: 49,
    Farm_Key: "BLC007",
    Produce_Type: "broccoli",
    season: "spring,fall",
    X: -105.1638278,
    Y: 40.11611101,
    Farm_Name: "Kilt Farm",
    Full_Addre: "8140 Oxford Rd. Niwot",
    Email: "michael@kiltfarm.com",
    Website: "www.kiltfarm.com",
  },
  {
    OID_: 48,
    ProduceDir: 50,
    Farm_Key: "BLC007",
    Produce_Type: "bell pepper",
    season: "summer,fall",
    X: -105.1638278,
    Y: 40.11611101,
    Farm_Name: "Kilt Farm",
    Full_Addre: "8140 Oxford Rd. Niwot",
    Email: "michael@kiltfarm.com",
    Website: "www.kiltfarm.com",
  },
  {
    OID_: 49,
    ProduceDir: 51,
    Farm_Key: "BLC007",
    Produce_Type: "cabbage",
    season: "spring,fall,winter",
    X: -105.1638278,
    Y: 40.11611101,
    Farm_Name: "Kilt Farm",
    Full_Addre: "8140 Oxford Rd. Niwot",
    Email: "michael@kiltfarm.com",
    Website: "www.kiltfarm.com",
  },
  {
    OID_: 50,
    ProduceDir: 52,
    Farm_Key: "BLC007",
    Produce_Type: "carrot",
    season: "spring,summer,fall,winter",
    X: -105.1638278,
    Y: 40.11611101,
    Farm_Name: "Kilt Farm",
    Full_Addre: "8140 Oxford Rd. Niwot",
    Email: "michael@kiltfarm.com",
    Website: "www.kiltfarm.com",
  },
  {
    OID_: 51,
    ProduceDir: 53,
    Farm_Key: "BLC007",
    Produce_Type: "cucumber",
    season: "summer",
    X: -105.1638278,
    Y: 40.11611101,
    Farm_Name: "Kilt Farm",
    Full_Addre: "8140 Oxford Rd. Niwot",
    Email: "michael@kiltfarm.com",
    Website: "www.kiltfarm.com",
  },
  {
    OID_: 52,
    ProduceDir: 54,
    Farm_Key: "BLC007",
    Produce_Type: "eggplant",
    season: "summer",
    X: -105.1638278,
    Y: 40.11611101,
    Farm_Name: "Kilt Farm",
    Full_Addre: "8140 Oxford Rd. Niwot",
    Email: "michael@kiltfarm.com",
    Website: "www.kiltfarm.com",
  },
  {
    OID_: 53,
    ProduceDir: 55,
    Farm_Key: "BLC007",
    Produce_Type: "cantaloupe",
    season: "summer",
    X: -105.1638278,
    Y: 40.11611101,
    Farm_Name: "Kilt Farm",
    Full_Addre: "8140 Oxford Rd. Niwot",
    Email: "michael@kiltfarm.com",
    Website: "www.kiltfarm.com",
  },
  {
    OID_: 54,
    ProduceDir: 56,
    Farm_Key: "BLC007",
    Produce_Type: "garlic",
    season: "spring,summer,fall",
    X: -105.1638278,
    Y: 40.11611101,
    Farm_Name: "Kilt Farm",
    Full_Addre: "8140 Oxford Rd. Niwot",
    Email: "michael@kiltfarm.com",
    Website: "www.kiltfarm.com",
  },
  {
    OID_: 55,
    ProduceDir: 57,
    Farm_Key: "BLC007",
    Produce_Type: "green beans",
    season: "summer,fall",
    X: -105.1638278,
    Y: 40.11611101,
    Farm_Name: "Kilt Farm",
    Full_Addre: "8140 Oxford Rd. Niwot",
    Email: "michael@kiltfarm.com",
    Website: "www.kiltfarm.com",
  },
  {
    OID_: 56,
    ProduceDir: 58,
    Farm_Key: "BLC007",
    Produce_Type: "mixed herbs",
    season: "spring,summer,fall,winter",
    X: -105.1638278,
    Y: 40.11611101,
    Farm_Name: "Kilt Farm",
    Full_Addre: "8140 Oxford Rd. Niwot",
    Email: "michael@kiltfarm.com",
    Website: "www.kiltfarm.com",
  },
  {
    OID_: 57,
    ProduceDir: 59,
    Farm_Key: "BLC007",
    Produce_Type: "honeydew melon",
    season: "summer",
    X: -105.1638278,
    Y: 40.11611101,
    Farm_Name: "Kilt Farm",
    Full_Addre: "8140 Oxford Rd. Niwot",
    Email: "michael@kiltfarm.com",
    Website: "www.kiltfarm.com",
  },
  {
    OID_: 58,
    ProduceDir: 60,
    Farm_Key: "BLC007",
    Produce_Type: "lettuce",
    season: "spring,fall",
    X: -105.1638278,
    Y: 40.11611101,
    Farm_Name: "Kilt Farm",
    Full_Addre: "8140 Oxford Rd. Niwot",
    Email: "michael@kiltfarm.com",
    Website: "www.kiltfarm.com",
  },
  {
    OID_: 59,
    ProduceDir: 61,
    Farm_Key: "BLC007",
    Produce_Type: "onion",
    season: "spring,fall,winter",
    X: -105.1638278,
    Y: 40.11611101,
    Farm_Name: "Kilt Farm",
    Full_Addre: "8140 Oxford Rd. Niwot",
    Email: "michael@kiltfarm.com",
    Website: "www.kiltfarm.com",
  },
  {
    OID_: 60,
    ProduceDir: 62,
    Farm_Key: "BLC007",
    Produce_Type: "leek",
    season: "winter",
    X: -105.1638278,
    Y: 40.11611101,
    Farm_Name: "Kilt Farm",
    Full_Addre: "8140 Oxford Rd. Niwot",
    Email: "michael@kiltfarm.com",
    Website: "www.kiltfarm.com",
  },
  {
    OID_: 61,
    ProduceDir: 63,
    Farm_Key: "BLC007",
    Produce_Type: "pumpkin",
    season: "fall,winter",
    X: -105.1638278,
    Y: 40.11611101,
    Farm_Name: "Kilt Farm",
    Full_Addre: "8140 Oxford Rd. Niwot",
    Email: "michael@kiltfarm.com",
    Website: "www.kiltfarm.com",
  },
  {
    OID_: 62,
    ProduceDir: 64,
    Farm_Key: "BLC007",
    Produce_Type: "peas",
    season: "spring,fall",
    X: -105.1638278,
    Y: 40.11611101,
    Farm_Name: "Kilt Farm",
    Full_Addre: "8140 Oxford Rd. Niwot",
    Email: "michael@kiltfarm.com",
    Website: "www.kiltfarm.com",
  },
  {
    OID_: 63,
    ProduceDir: 65,
    Farm_Key: "BLC008",
    Produce_Type: "watermelon",
    season: "summer",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 64,
    ProduceDir: 66,
    Farm_Key: "BLC007",
    Produce_Type: "summer squash",
    season: "summer",
    X: -105.1638278,
    Y: 40.11611101,
    Farm_Name: "Kilt Farm",
    Full_Addre: "8140 Oxford Rd. Niwot",
    Email: "michael@kiltfarm.com",
    Website: "www.kiltfarm.com",
  },
  {
    OID_: 65,
    ProduceDir: 67,
    Farm_Key: "BLC007",
    Produce_Type: "radish",
    season: "spring,fall",
    X: -105.1638278,
    Y: 40.11611101,
    Farm_Name: "Kilt Farm",
    Full_Addre: "8140 Oxford Rd. Niwot",
    Email: "michael@kiltfarm.com",
    Website: "www.kiltfarm.com",
  },
  {
    OID_: 66,
    ProduceDir: 68,
    Farm_Key: "BLC007",
    Produce_Type: "spinach",
    season: "spring,fall",
    X: -105.1638278,
    Y: 40.11611101,
    Farm_Name: "Kilt Farm",
    Full_Addre: "8140 Oxford Rd. Niwot",
    Email: "michael@kiltfarm.com",
    Website: "www.kiltfarm.com",
  },
  {
    OID_: 67,
    ProduceDir: 69,
    Farm_Key: "BLC008",
    Produce_Type: "zucchini",
    season: "summer",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 68,
    ProduceDir: 70,
    Farm_Key: "BLC008",
    Produce_Type: "apple",
    season: "spring,summer,fall,winter",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 69,
    ProduceDir: 71,
    Farm_Key: "BLC007",
    Produce_Type: "turnip",
    season: "spring,fall,winter",
    X: -105.1638278,
    Y: 40.11611101,
    Farm_Name: "Kilt Farm",
    Full_Addre: "8140 Oxford Rd. Niwot",
    Email: "michael@kiltfarm.com",
    Website: "www.kiltfarm.com",
  },
  {
    OID_: 70,
    ProduceDir: 72,
    Farm_Key: "BLC007",
    Produce_Type: "tomato",
    season: "summer",
    X: -105.1638278,
    Y: 40.11611101,
    Farm_Name: "Kilt Farm",
    Full_Addre: "8140 Oxford Rd. Niwot",
    Email: "michael@kiltfarm.com",
    Website: "www.kiltfarm.com",
  },
  {
    OID_: 71,
    ProduceDir: 73,
    Farm_Key: "BLC008",
    Produce_Type: "apricot",
    season: "spring,summer",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 72,
    ProduceDir: 74,
    Farm_Key: "BLC008",
    Produce_Type: "bell pepper",
    season: "summer,fall",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 73,
    ProduceDir: 75,
    Farm_Key: "BLC008",
    Produce_Type: "asparagus",
    season: "spring",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 74,
    ProduceDir: 76,
    Farm_Key: "BLC008",
    Produce_Type: "brussels sprout",
    season: "fall,winter",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 75,
    ProduceDir: 77,
    Farm_Key: "BLC008",
    Produce_Type: "broccoli",
    season: "spring,fall",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 76,
    ProduceDir: 78,
    Farm_Key: "BLC008",
    Produce_Type: "cantaloupe",
    season: "summer",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 77,
    ProduceDir: 79,
    Farm_Key: "BLC008",
    Produce_Type: "cauliflower",
    season: "fall",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 78,
    ProduceDir: 80,
    Farm_Key: "BLC008",
    Produce_Type: "cabbage",
    season: "spring,fall,winter",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 79,
    ProduceDir: 81,
    Farm_Key: "BLC008",
    Produce_Type: "carrot",
    season: "spring,summer,fall,winter",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 80,
    ProduceDir: 82,
    Farm_Key: "BLC008",
    Produce_Type: "celery",
    season: "spring,summer,fall,winter",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 81,
    ProduceDir: 83,
    Farm_Key: "BLC008",
    Produce_Type: "cherry",
    season: "summer",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 82,
    ProduceDir: 84,
    Farm_Key: "BLC008",
    Produce_Type: "fire-roasted green chiles",
    season: "spring,summer,fall,winter",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 83,
    ProduceDir: 85,
    Farm_Key: "BLC008",
    Produce_Type: "chile pepper",
    season: "summer,fall",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 84,
    ProduceDir: 86,
    Farm_Key: "BLC008",
    Produce_Type: "eggplant",
    season: "summer",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 85,
    ProduceDir: 87,
    Farm_Key: "BLC008",
    Produce_Type: "green beans",
    season: "summer,fall",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 86,
    ProduceDir: 88,
    Farm_Key: "BLC008",
    Produce_Type: "cucumber",
    season: "summer",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 87,
    ProduceDir: 89,
    Farm_Key: "BLC008",
    Produce_Type: "garlic",
    season: "spring,summer,fall",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 88,
    ProduceDir: 90,
    Farm_Key: "BLC008",
    Produce_Type: "honeydew melon",
    season: "summer",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 89,
    ProduceDir: 91,
    Farm_Key: "BLC008",
    Produce_Type: "leek",
    season: "winter",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 90,
    ProduceDir: 92,
    Farm_Key: "BLC008",
    Produce_Type: "mixed herbs",
    season: "spring,summer,fall,winter",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 91,
    ProduceDir: 93,
    Farm_Key: "BLC008",
    Produce_Type: "kale",
    season: "spring,fall,winter",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 92,
    ProduceDir: 94,
    Farm_Key: "BLC008",
    Produce_Type: "lettuce",
    season: "spring,fall",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 93,
    ProduceDir: 95,
    Farm_Key: "BLC008",
    Produce_Type: "microgreens",
    season: "spring,summer,fall,winter",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 94,
    ProduceDir: 96,
    Farm_Key: "BLC008",
    Produce_Type: "mixed mushrooms",
    season: "spring,summer,fall,winter",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 95,
    ProduceDir: 97,
    Farm_Key: "BLC008",
    Produce_Type: "nectarine",
    season: "summer",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 96,
    ProduceDir: 98,
    Farm_Key: "BLC008",
    Produce_Type: "okra",
    season: "summer",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 97,
    ProduceDir: 99,
    Farm_Key: "BLC008",
    Produce_Type: "onion",
    season: "spring,fall,winter",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 98,
    ProduceDir: 100,
    Farm_Key: "BLC008",
    Produce_Type: "peach",
    season: "summer",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 99,
    ProduceDir: 101,
    Farm_Key: "BLC008",
    Produce_Type: "pear",
    season: "fall,winter",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 100,
    ProduceDir: 102,
    Farm_Key: "BLC008",
    Produce_Type: "peas",
    season: "spring,fall",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 101,
    ProduceDir: 103,
    Farm_Key: "BLC008",
    Produce_Type: "pinto beans",
    season: "spring,summer,fall,winter",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 102,
    ProduceDir: 104,
    Farm_Key: "BLC008",
    Produce_Type: "plum",
    season: "summer",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 103,
    ProduceDir: 105,
    Farm_Key: "BLC008",
    Produce_Type: "potato",
    season: "fall,winter",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 104,
    ProduceDir: 106,
    Farm_Key: "BLC008",
    Produce_Type: "radish",
    season: "spring,fall",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 105,
    ProduceDir: 107,
    Farm_Key: "BLC008",
    Produce_Type: "pumpkin",
    season: "fall,winter",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 106,
    ProduceDir: 108,
    Farm_Key: "BLC008",
    Produce_Type: "rhubarb",
    season: "spring",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 107,
    ProduceDir: 109,
    Farm_Key: "BLC008",
    Produce_Type: "raspberry",
    season: "summer,fall",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 108,
    ProduceDir: 110,
    Farm_Key: "BLC008",
    Produce_Type: "summer squash",
    season: "summer",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 109,
    ProduceDir: 111,
    Farm_Key: "BLC008",
    Produce_Type: "spinach",
    season: "spring,fall",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 110,
    ProduceDir: 112,
    Farm_Key: "BLC008",
    Produce_Type: "sweet corn",
    season: "summer",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 111,
    ProduceDir: 113,
    Farm_Key: "BLC008",
    Produce_Type: "strawberry",
    season: "spring,summer",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 112,
    ProduceDir: 114,
    Farm_Key: "BLC008",
    Produce_Type: "tomato",
    season: "summer",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 113,
    ProduceDir: 115,
    Farm_Key: "BLC008",
    Produce_Type: "turnip",
    season: "spring,fall,winter",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 114,
    ProduceDir: 116,
    Farm_Key: "BLC008",
    Produce_Type: "watermelon",
    season: "summer",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 115,
    ProduceDir: 117,
    Farm_Key: "BLC008",
    Produce_Type: "zucchini",
    season: "summer",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 116,
    ProduceDir: 118,
    Farm_Key: "BLC008",
    Produce_Type: "cider",
    season: "spring,summer,fall,winter",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 117,
    ProduceDir: 119,
    Farm_Key: "BLC008",
    Produce_Type: "honey",
    season: "spring,summer,fall,winter",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 118,
    ProduceDir: 120,
    Farm_Key: "BLC008",
    Produce_Type: "egg",
    season: "spring,summer,fall,winter",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 119,
    ProduceDir: 121,
    Farm_Key: "BLC008",
    Produce_Type: "jam",
    season: "spring,summer,fall,winter",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 120,
    ProduceDir: 122,
    Farm_Key: "BLC008",
    Produce_Type: "popcorn",
    season: "spring,summer,fall,winter",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 121,
    ProduceDir: 123,
    Farm_Key: "BLC008",
    Produce_Type: "pickle",
    season: "spring,summer,fall,winter",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 122,
    ProduceDir: 124,
    Farm_Key: "BLC008",
    Produce_Type: "ground lamb",
    season: "spring,summer,fall,winter",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 123,
    ProduceDir: 125,
    Farm_Key: "BLC008",
    Produce_Type: "ground beef",
    season: "spring,summer,fall,winter",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 124,
    ProduceDir: 126,
    Farm_Key: "BLC008",
    Produce_Type: "ground pork",
    season: "spring,summer,fall,winter",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 125,
    ProduceDir: 127,
    Farm_Key: "BLC008",
    Produce_Type: "chicken breast",
    season: "spring,summer,fall,winter",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 126,
    ProduceDir: 128,
    Farm_Key: "BLC008",
    Produce_Type: "sausage",
    season: "spring,summer,fall,winter",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 127,
    ProduceDir: 129,
    Farm_Key: "BLC008",
    Produce_Type: "salmon",
    season: "spring,summer,fall,winter",
    X: -105.1307325,
    Y: 39.9784126,
    Farm_Name: "Louisville Farmers Market",
    Full_Addre: "824 Front St. Louisville, CO",
    Email: "kellyenterprisesltd@gmail.com",
    Website: "www.realfarmersmarketco.com",
  },
  {
    OID_: 128,
    ProduceDir: 130,
    Farm_Key: "BLC009",
    Produce_Type: "apple",
    season: "spring,summer,fall,winter",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 129,
    ProduceDir: 131,
    Farm_Key: "BLC009",
    Produce_Type: "zucchini",
    season: "summer",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 130,
    ProduceDir: 132,
    Farm_Key: "BLC009",
    Produce_Type: "asparagus",
    season: "spring",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 131,
    ProduceDir: 133,
    Farm_Key: "BLC009",
    Produce_Type: "apricot",
    season: "spring,summer",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 132,
    ProduceDir: 134,
    Farm_Key: "BLC009",
    Produce_Type: "broccoli",
    season: "spring,fall",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 133,
    ProduceDir: 135,
    Farm_Key: "BLC009",
    Produce_Type: "bell pepper",
    season: "summer,fall",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 134,
    ProduceDir: 136,
    Farm_Key: "BLC009",
    Produce_Type: "brussels sprout",
    season: "fall,winter",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 135,
    ProduceDir: 137,
    Farm_Key: "BLC009",
    Produce_Type: "cabbage",
    season: "spring,fall,winter",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 136,
    ProduceDir: 138,
    Farm_Key: "BLC009",
    Produce_Type: "cantaloupe",
    season: "summer",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 137,
    ProduceDir: 139,
    Farm_Key: "BLC009",
    Produce_Type: "carrot",
    season: "spring,summer,fall,winter",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 138,
    ProduceDir: 140,
    Farm_Key: "BLC009",
    Produce_Type: "cauliflower",
    season: "fall",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 139,
    ProduceDir: 141,
    Farm_Key: "BLC009",
    Produce_Type: "chile pepper",
    season: "summer,fall",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 140,
    ProduceDir: 142,
    Farm_Key: "BLC009",
    Produce_Type: "cucumber",
    season: "summer",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 141,
    ProduceDir: 143,
    Farm_Key: "BLC009",
    Produce_Type: "celery",
    season: "spring,summer,fall,winter",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 142,
    ProduceDir: 144,
    Farm_Key: "BLC009",
    Produce_Type: "cherry",
    season: "summer",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 143,
    ProduceDir: 145,
    Farm_Key: "BLC009",
    Produce_Type: "green beans",
    season: "summer,fall",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 144,
    ProduceDir: 146,
    Farm_Key: "BLC009",
    Produce_Type: "garlic",
    season: "spring,summer,fall",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 145,
    ProduceDir: 147,
    Farm_Key: "BLC009",
    Produce_Type: "eggplant",
    season: "summer",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 146,
    ProduceDir: 148,
    Farm_Key: "BLC009",
    Produce_Type: "mixed herbs",
    season: "spring,summer,fall,winter",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 147,
    ProduceDir: 149,
    Farm_Key: "BLC009",
    Produce_Type: "leek",
    season: "winter",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 148,
    ProduceDir: 150,
    Farm_Key: "BLC009",
    Produce_Type: "honeydew melon",
    season: "summer",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 149,
    ProduceDir: 151,
    Farm_Key: "BLC009",
    Produce_Type: "kale",
    season: "spring,fall,winter",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 150,
    ProduceDir: 152,
    Farm_Key: "BLC009",
    Produce_Type: "lettuce",
    season: "spring,fall",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 151,
    ProduceDir: 153,
    Farm_Key: "BLC009",
    Produce_Type: "nectarine",
    season: "summer",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 152,
    ProduceDir: 154,
    Farm_Key: "BLC009",
    Produce_Type: "microgreens",
    season: "spring,summer,fall,winter",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 153,
    ProduceDir: 155,
    Farm_Key: "BLC009",
    Produce_Type: "okra",
    season: "summer",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 154,
    ProduceDir: 156,
    Farm_Key: "BLC009",
    Produce_Type: "mixed mushrooms",
    season: "spring,summer,fall,winter",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 155,
    ProduceDir: 157,
    Farm_Key: "BLC009",
    Produce_Type: "onion",
    season: "spring,fall,winter",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 156,
    ProduceDir: 158,
    Farm_Key: "BLC009",
    Produce_Type: "pear",
    season: "fall,winter",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 157,
    ProduceDir: 159,
    Farm_Key: "BLC009",
    Produce_Type: "peas",
    season: "spring,fall",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 158,
    ProduceDir: 160,
    Farm_Key: "BLC009",
    Produce_Type: "peach",
    season: "summer",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 159,
    ProduceDir: 161,
    Farm_Key: "BLC009",
    Produce_Type: "potato",
    season: "fall,winter",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 160,
    ProduceDir: 162,
    Farm_Key: "BLC009",
    Produce_Type: "pumpkin",
    season: "fall,winter",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 161,
    ProduceDir: 163,
    Farm_Key: "BLC009",
    Produce_Type: "plum",
    season: "summer",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 162,
    ProduceDir: 164,
    Farm_Key: "BLC009",
    Produce_Type: "pinto beans",
    season: "spring,summer,fall,winter",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 163,
    ProduceDir: 165,
    Farm_Key: "BLC009",
    Produce_Type: "radish",
    season: "spring,fall",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 164,
    ProduceDir: 166,
    Farm_Key: "BLC009",
    Produce_Type: "raspberry",
    season: "summer,fall",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 165,
    ProduceDir: 167,
    Farm_Key: "BLC009",
    Produce_Type: "spinach",
    season: "spring,fall",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 166,
    ProduceDir: 168,
    Farm_Key: "BLC009",
    Produce_Type: "rhubarb",
    season: "spring",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 167,
    ProduceDir: 169,
    Farm_Key: "BLC009",
    Produce_Type: "sweet corn",
    season: "summer",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 168,
    ProduceDir: 170,
    Farm_Key: "BLC009",
    Produce_Type: "summer squash",
    season: "summer",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 169,
    ProduceDir: 171,
    Farm_Key: "BLC009",
    Produce_Type: "strawberry",
    season: "spring,summer",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 170,
    ProduceDir: 172,
    Farm_Key: "BLC009",
    Produce_Type: "tomato",
    season: "summer",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 171,
    ProduceDir: 173,
    Farm_Key: "BLC009",
    Produce_Type: "turnip",
    season: "spring,fall,winter",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 172,
    ProduceDir: 174,
    Farm_Key: "BLC009",
    Produce_Type: "watermelon",
    season: "summer",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 173,
    ProduceDir: 175,
    Farm_Key: "BLC009",
    Produce_Type: "cider",
    season: "spring,summer,fall,winter",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 174,
    ProduceDir: 176,
    Farm_Key: "BLC009",
    Produce_Type: "zucchini",
    season: "summer",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 175,
    ProduceDir: 177,
    Farm_Key: "BLC009",
    Produce_Type: "egg",
    season: "spring,summer,fall,winter",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 176,
    ProduceDir: 178,
    Farm_Key: "BLC009",
    Produce_Type: "honey",
    season: "spring,summer,fall,winter",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 177,
    ProduceDir: 179,
    Farm_Key: "BLC009",
    Produce_Type: "jam",
    season: "spring,summer,fall,winter",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 178,
    ProduceDir: 180,
    Farm_Key: "BLC009",
    Produce_Type: "pickle",
    season: "spring,summer,fall,winter",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 179,
    ProduceDir: 181,
    Farm_Key: "BLC009",
    Produce_Type: "popcorn",
    season: "spring,summer,fall,winter",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 180,
    ProduceDir: 182,
    Farm_Key: "BLC009",
    Produce_Type: "ground lamb",
    season: "spring,summer,fall,winter",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 181,
    ProduceDir: 183,
    Farm_Key: "BLC009",
    Produce_Type: "ground beef",
    season: "spring,summer,fall,winter",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 182,
    ProduceDir: 184,
    Farm_Key: "BLC010",
    Produce_Type: "pumpkin",
    season: "fall,winter",
    X: -105.14148,
    Y: 40.20333729,
    Farm_Name: "Rocky Mountain Pumpkin Ranch",
    Full_Addre: "9059 Ute Hwy. Longmont, CO",
    Email: "info@rmpr.farm",
    Website: "www.rockymtnpumpkinranch.com",
  },
  {
    OID_: 183,
    ProduceDir: 185,
    Farm_Key: "BLC009",
    Produce_Type: "ground pork",
    season: "spring,summer,fall,winter",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 184,
    ProduceDir: 186,
    Farm_Key: "BLC010",
    Produce_Type: "cider",
    season: "spring,summer,fall,winter",
    X: -105.14148,
    Y: 40.20333729,
    Farm_Name: "Rocky Mountain Pumpkin Ranch",
    Full_Addre: "9059 Ute Hwy. Longmont, CO",
    Email: "info@rmpr.farm",
    Website: "www.rockymtnpumpkinranch.com",
  },
  {
    OID_: 185,
    ProduceDir: 187,
    Farm_Key: "BLC009",
    Produce_Type: "chicken breast",
    season: "spring,summer,fall,winter",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 186,
    ProduceDir: 188,
    Farm_Key: "BLC009",
    Produce_Type: "sausage",
    season: "spring,summer,fall,winter",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 187,
    ProduceDir: 189,
    Farm_Key: "BLC010",
    Produce_Type: "butter",
    season: "spring,summer,fall,winter",
    X: -105.14148,
    Y: 40.20333729,
    Farm_Name: "Rocky Mountain Pumpkin Ranch",
    Full_Addre: "9059 Ute Hwy. Longmont, CO",
    Email: "info@rmpr.farm",
    Website: "www.rockymtnpumpkinranch.com",
  },
  {
    OID_: 188,
    ProduceDir: 190,
    Farm_Key: "BLC010",
    Produce_Type: "jam",
    season: "spring,summer,fall,winter",
    X: -105.14148,
    Y: 40.20333729,
    Farm_Name: "Rocky Mountain Pumpkin Ranch",
    Full_Addre: "9059 Ute Hwy. Longmont, CO",
    Email: "info@rmpr.farm",
    Website: "www.rockymtnpumpkinranch.com",
  },
  {
    OID_: 189,
    ProduceDir: 191,
    Farm_Key: "BLC010",
    Produce_Type: "salsa",
    season: "spring,summer,fall,winter",
    X: -105.14148,
    Y: 40.20333729,
    Farm_Name: "Rocky Mountain Pumpkin Ranch",
    Full_Addre: "9059 Ute Hwy. Longmont, CO",
    Email: "info@rmpr.farm",
    Website: "www.rockymtnpumpkinranch.com",
  },
  {
    OID_: 190,
    ProduceDir: 192,
    Farm_Key: "BLC009",
    Produce_Type: "salmon",
    season: "spring,summer,fall,winter",
    X: -105.5088829,
    Y: 39.9619373,
    Farm_Name: "Nederland Farmers’ Market",
    Full_Addre: "85 E. First St. Nederland, CO",
    Email: "vending@nederlandfarmersmarket.org",
    Website: "www.nederlandfarmersmarket.org",
  },
  {
    OID_: 191,
    ProduceDir: 193,
    Farm_Key: "BLC010",
    Produce_Type: "honey",
    season: "spring,summer,fall,winter",
    X: -105.14148,
    Y: 40.20333729,
    Farm_Name: "Rocky Mountain Pumpkin Ranch",
    Full_Addre: "9059 Ute Hwy. Longmont, CO",
    Email: "info@rmpr.farm",
    Website: "www.rockymtnpumpkinranch.com",
  },
  {
    OID_: 192,
    ProduceDir: 194,
    Farm_Key: "BLC011",
    Produce_Type: "beetroot",
    season: "summer,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 193,
    ProduceDir: 195,
    Farm_Key: "BLC011",
    Produce_Type: "bell pepper",
    season: "summer,fall",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 194,
    ProduceDir: 196,
    Farm_Key: "BLC011",
    Produce_Type: "broccoli",
    season: "spring,fall",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 195,
    ProduceDir: 197,
    Farm_Key: "BLC011",
    Produce_Type: "cabbage",
    season: "spring,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 196,
    ProduceDir: 198,
    Farm_Key: "BLC011",
    Produce_Type: "cantaloupe",
    season: "summer",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 197,
    ProduceDir: 199,
    Farm_Key: "BLC011",
    Produce_Type: "carrot",
    season: "spring,summer,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 198,
    ProduceDir: 200,
    Farm_Key: "BLC011",
    Produce_Type: "chile pepper",
    season: "summer,fall",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 199,
    ProduceDir: 201,
    Farm_Key: "BLC011",
    Produce_Type: "cucumber",
    season: "summer",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 200,
    ProduceDir: 202,
    Farm_Key: "BLC011",
    Produce_Type: "green beans",
    season: "summer,fall",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 201,
    ProduceDir: 203,
    Farm_Key: "BLC011",
    Produce_Type: "mixed herbs",
    season: "spring,summer,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 202,
    ProduceDir: 204,
    Farm_Key: "BLC011",
    Produce_Type: "honeydew melon",
    season: "summer",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 203,
    ProduceDir: 205,
    Farm_Key: "BLC011",
    Produce_Type: "lettuce",
    season: "spring,fall",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 204,
    ProduceDir: 206,
    Farm_Key: "BLC011",
    Produce_Type: "onion",
    season: "spring,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 205,
    ProduceDir: 207,
    Farm_Key: "BLC011",
    Produce_Type: "pickle",
    season: "spring,summer,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 206,
    ProduceDir: 208,
    Farm_Key: "BLC011",
    Produce_Type: "pumpkin",
    season: "fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 207,
    ProduceDir: 209,
    Farm_Key: "BLC011",
    Produce_Type: "summer squash",
    season: "summer",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 208,
    ProduceDir: 210,
    Farm_Key: "BLC011",
    Produce_Type: "spinach",
    season: "spring,fall",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 209,
    ProduceDir: 211,
    Farm_Key: "BLC011",
    Produce_Type: "sweet corn",
    season: "summer",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 210,
    ProduceDir: 212,
    Farm_Key: "BLC011",
    Produce_Type: "tomato",
    season: "summer",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 211,
    ProduceDir: 213,
    Farm_Key: "BLC011",
    Produce_Type: "turnip",
    season: "spring,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 212,
    ProduceDir: 214,
    Farm_Key: "BLC011",
    Produce_Type: "watermelon",
    season: "summer",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 213,
    ProduceDir: 215,
    Farm_Key: "BLC011",
    Produce_Type: "zucchini",
    season: "summer",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 214,
    ProduceDir: 216,
    Farm_Key: "BLC012",
    Produce_Type: "beetroot",
    season: "summer,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 215,
    ProduceDir: 217,
    Farm_Key: "BLC012",
    Produce_Type: "bell pepper",
    season: "summer,fall",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 216,
    ProduceDir: 218,
    Farm_Key: "BLC012",
    Produce_Type: "broccoli",
    season: "spring,fall",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 217,
    ProduceDir: 219,
    Farm_Key: "BLC012",
    Produce_Type: "cabbage",
    season: "spring,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 218,
    ProduceDir: 220,
    Farm_Key: "BLC012",
    Produce_Type: "cantaloupe",
    season: "summer",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 219,
    ProduceDir: 221,
    Farm_Key: "BLC012",
    Produce_Type: "carrot",
    season: "spring,summer,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 220,
    ProduceDir: 222,
    Farm_Key: "BLC012",
    Produce_Type: "chile pepper",
    season: "summer,fall",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 221,
    ProduceDir: 223,
    Farm_Key: "BLC012",
    Produce_Type: "cucumber",
    season: "summer",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 222,
    ProduceDir: 224,
    Farm_Key: "BLC012",
    Produce_Type: "green beans",
    season: "summer,fall",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 223,
    ProduceDir: 225,
    Farm_Key: "BLC012",
    Produce_Type: "mixed herbs",
    season: "spring,summer,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 224,
    ProduceDir: 226,
    Farm_Key: "BLC012",
    Produce_Type: "honeydew melon",
    season: "summer",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 225,
    ProduceDir: 227,
    Farm_Key: "BLC012",
    Produce_Type: "lettuce",
    season: "spring,fall",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 226,
    ProduceDir: 228,
    Farm_Key: "BLC012",
    Produce_Type: "onion",
    season: "spring,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 227,
    ProduceDir: 229,
    Farm_Key: "BLC012",
    Produce_Type: "pickle",
    season: "spring,summer,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 228,
    ProduceDir: 230,
    Farm_Key: "BLC012",
    Produce_Type: "pumpkin",
    season: "fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 229,
    ProduceDir: 231,
    Farm_Key: "BLC012",
    Produce_Type: "summer squash",
    season: "summer",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 230,
    ProduceDir: 232,
    Farm_Key: "BLC012",
    Produce_Type: "spinach",
    season: "spring,fall",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 231,
    ProduceDir: 233,
    Farm_Key: "BLC012",
    Produce_Type: "sweet corn",
    season: "summer",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 232,
    ProduceDir: 234,
    Farm_Key: "BLC012",
    Produce_Type: "tomato",
    season: "summer",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 233,
    ProduceDir: 235,
    Farm_Key: "BLC012",
    Produce_Type: "turnip",
    season: "spring,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 234,
    ProduceDir: 236,
    Farm_Key: "BLC012",
    Produce_Type: "watermelon",
    season: "summer",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 235,
    ProduceDir: 237,
    Farm_Key: "BLC012",
    Produce_Type: "zucchini",
    season: "summer",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 236,
    ProduceDir: 238,
    Farm_Key: "BLC012",
    Produce_Type: "ground beef",
    season: "spring,summer,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 237,
    ProduceDir: 239,
    Farm_Key: "BLC012",
    Produce_Type: "jam",
    season: "spring,summer,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 238,
    ProduceDir: 240,
    Farm_Key: "BLC012",
    Produce_Type: "peas",
    season: "spring,fall",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 239,
    ProduceDir: 241,
    Farm_Key: "BLC013",
    Produce_Type: "apple",
    season: "spring,summer,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 240,
    ProduceDir: 242,
    Farm_Key: "BLC013",
    Produce_Type: "zucchini",
    season: "summer",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 241,
    ProduceDir: 243,
    Farm_Key: "BLC013",
    Produce_Type: "asparagus",
    season: "spring",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 242,
    ProduceDir: 244,
    Farm_Key: "BLC013",
    Produce_Type: "apricot",
    season: "spring,summer",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 243,
    ProduceDir: 245,
    Farm_Key: "BLC013",
    Produce_Type: "broccoli",
    season: "spring,fall",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 244,
    ProduceDir: 246,
    Farm_Key: "BLC013",
    Produce_Type: "bell pepper",
    season: "summer,fall",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 245,
    ProduceDir: 247,
    Farm_Key: "BLC013",
    Produce_Type: "brussels sprout",
    season: "fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 246,
    ProduceDir: 248,
    Farm_Key: "BLC013",
    Produce_Type: "cabbage",
    season: "spring,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 247,
    ProduceDir: 249,
    Farm_Key: "BLC013",
    Produce_Type: "cantaloupe",
    season: "summer",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 248,
    ProduceDir: 250,
    Farm_Key: "BLC013",
    Produce_Type: "carrot",
    season: "spring,summer,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 249,
    ProduceDir: 251,
    Farm_Key: "BLC013",
    Produce_Type: "cauliflower",
    season: "fall",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 250,
    ProduceDir: 252,
    Farm_Key: "BLC013",
    Produce_Type: "chile pepper",
    season: "summer,fall",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 251,
    ProduceDir: 253,
    Farm_Key: "BLC013",
    Produce_Type: "cucumber",
    season: "summer",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 252,
    ProduceDir: 254,
    Farm_Key: "BLC013",
    Produce_Type: "celery",
    season: "spring,summer,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 253,
    ProduceDir: 255,
    Farm_Key: "BLC013",
    Produce_Type: "cherry",
    season: "summer",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 254,
    ProduceDir: 256,
    Farm_Key: "BLC013",
    Produce_Type: "green beans",
    season: "summer,fall",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 255,
    ProduceDir: 257,
    Farm_Key: "BLC013",
    Produce_Type: "garlic",
    season: "spring,summer,fall",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 256,
    ProduceDir: 258,
    Farm_Key: "BLC013",
    Produce_Type: "eggplant",
    season: "summer",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 257,
    ProduceDir: 259,
    Farm_Key: "BLC013",
    Produce_Type: "mixed herbs",
    season: "spring,summer,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 258,
    ProduceDir: 260,
    Farm_Key: "BLC013",
    Produce_Type: "leek",
    season: "winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 259,
    ProduceDir: 261,
    Farm_Key: "BLC013",
    Produce_Type: "honeydew melon",
    season: "summer",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 260,
    ProduceDir: 262,
    Farm_Key: "BLC013",
    Produce_Type: "kale",
    season: "spring,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 261,
    ProduceDir: 263,
    Farm_Key: "BLC013",
    Produce_Type: "lettuce",
    season: "spring,fall",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 262,
    ProduceDir: 264,
    Farm_Key: "BLC013",
    Produce_Type: "nectarine",
    season: "summer",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 263,
    ProduceDir: 265,
    Farm_Key: "BLC013",
    Produce_Type: "microgreens",
    season: "spring,summer,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 264,
    ProduceDir: 266,
    Farm_Key: "BLC013",
    Produce_Type: "okra",
    season: "summer",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 265,
    ProduceDir: 267,
    Farm_Key: "BLC013",
    Produce_Type: "mixed mushrooms",
    season: "spring,summer,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 266,
    ProduceDir: 268,
    Farm_Key: "BLC013",
    Produce_Type: "onion",
    season: "spring,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 267,
    ProduceDir: 269,
    Farm_Key: "BLC013",
    Produce_Type: "pear",
    season: "fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 268,
    ProduceDir: 270,
    Farm_Key: "BLC013",
    Produce_Type: "peas",
    season: "spring,fall",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 269,
    ProduceDir: 271,
    Farm_Key: "BLC013",
    Produce_Type: "peach",
    season: "summer",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 270,
    ProduceDir: 272,
    Farm_Key: "BLC013",
    Produce_Type: "potato",
    season: "fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 271,
    ProduceDir: 273,
    Farm_Key: "BLC013",
    Produce_Type: "pumpkin",
    season: "fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 272,
    ProduceDir: 274,
    Farm_Key: "BLC013",
    Produce_Type: "plum",
    season: "summer",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 273,
    ProduceDir: 275,
    Farm_Key: "BLC013",
    Produce_Type: "pinto beans",
    season: "spring,summer,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 274,
    ProduceDir: 276,
    Farm_Key: "BLC013",
    Produce_Type: "radish",
    season: "spring,fall",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 275,
    ProduceDir: 277,
    Farm_Key: "BLC013",
    Produce_Type: "raspberry",
    season: "summer,fall",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 276,
    ProduceDir: 278,
    Farm_Key: "BLC013",
    Produce_Type: "spinach",
    season: "spring,fall",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 277,
    ProduceDir: 279,
    Farm_Key: "BLC013",
    Produce_Type: "rhubarb",
    season: "spring",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 278,
    ProduceDir: 280,
    Farm_Key: "BLC013",
    Produce_Type: "sweet corn",
    season: "summer",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 279,
    ProduceDir: 281,
    Farm_Key: "BLC013",
    Produce_Type: "summer squash",
    season: "summer",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 280,
    ProduceDir: 282,
    Farm_Key: "BLC013",
    Produce_Type: "strawberry",
    season: "spring,summer",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 281,
    ProduceDir: 283,
    Farm_Key: "BLC013",
    Produce_Type: "tomato",
    season: "summer",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 282,
    ProduceDir: 284,
    Farm_Key: "BLC013",
    Produce_Type: "turnip",
    season: "spring,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 283,
    ProduceDir: 285,
    Farm_Key: "BLC013",
    Produce_Type: "watermelon",
    season: "summer",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 284,
    ProduceDir: 286,
    Farm_Key: "BLC013",
    Produce_Type: "cider",
    season: "spring,summer,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 285,
    ProduceDir: 287,
    Farm_Key: "BLC013",
    Produce_Type: "zucchini",
    season: "summer",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 286,
    ProduceDir: 288,
    Farm_Key: "BLC013",
    Produce_Type: "egg",
    season: "spring,summer,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 287,
    ProduceDir: 289,
    Farm_Key: "BLC013",
    Produce_Type: "honey",
    season: "spring,summer,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 288,
    ProduceDir: 290,
    Farm_Key: "BLC013",
    Produce_Type: "jam",
    season: "spring,summer,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 289,
    ProduceDir: 291,
    Farm_Key: "BLC013",
    Produce_Type: "pickle",
    season: "spring,summer,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 290,
    ProduceDir: 292,
    Farm_Key: "BLC013",
    Produce_Type: "popcorn",
    season: "spring,summer,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 291,
    ProduceDir: 293,
    Farm_Key: "BLC013",
    Produce_Type: "ground lamb",
    season: "spring,summer,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 292,
    ProduceDir: 294,
    Farm_Key: "BLC013",
    Produce_Type: "ground beef",
    season: "spring,summer,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 293,
    ProduceDir: 295,
    Farm_Key: "BLC014",
    Produce_Type: "honey",
    season: "spring,summer,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 294,
    ProduceDir: 296,
    Farm_Key: "BLC015",
    Produce_Type: "mixed mushrooms",
    season: "spring,summer,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 295,
    ProduceDir: 297,
    Farm_Key: "BLC016",
    Produce_Type: "bell pepper",
    season: "summer,fall",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 296,
    ProduceDir: 298,
    Farm_Key: "BLC016",
    Produce_Type: "beetroot",
    season: "summer,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 297,
    ProduceDir: 299,
    Farm_Key: "BLC016",
    Produce_Type: "cabbage",
    season: "spring,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 298,
    ProduceDir: 301,
    Farm_Key: "BLC016",
    Produce_Type: "broccoli",
    season: "spring,fall",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 299,
    ProduceDir: 302,
    Farm_Key: "BLC016",
    Produce_Type: "bell pepper",
    season: "summer,fall",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 300,
    ProduceDir: 303,
    Farm_Key: "BLC016",
    Produce_Type: "cabbage",
    season: "spring,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 301,
    ProduceDir: 304,
    Farm_Key: "BLC016",
    Produce_Type: "carrot",
    season: "spring,summer,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 302,
    ProduceDir: 305,
    Farm_Key: "BLC016",
    Produce_Type: "cucumber",
    season: "summer",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 303,
    ProduceDir: 306,
    Farm_Key: "BLC016",
    Produce_Type: "eggplant",
    season: "summer",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 304,
    ProduceDir: 307,
    Farm_Key: "BLC016",
    Produce_Type: "cantaloupe",
    season: "summer",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 305,
    ProduceDir: 308,
    Farm_Key: "BLC016",
    Produce_Type: "garlic",
    season: "spring,summer,fall",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 306,
    ProduceDir: 309,
    Farm_Key: "BLC016",
    Produce_Type: "green beans",
    season: "summer,fall",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 307,
    ProduceDir: 310,
    Farm_Key: "BLC016",
    Produce_Type: "mixed herbs",
    season: "spring,summer,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 308,
    ProduceDir: 311,
    Farm_Key: "BLC016",
    Produce_Type: "honeydew melon",
    season: "summer",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 309,
    ProduceDir: 312,
    Farm_Key: "BLC016",
    Produce_Type: "lettuce",
    season: "spring,fall",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 310,
    ProduceDir: 313,
    Farm_Key: "BLC016",
    Produce_Type: "onion",
    season: "spring,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 311,
    ProduceDir: 314,
    Farm_Key: "BLC016",
    Produce_Type: "leek",
    season: "winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 312,
    ProduceDir: 315,
    Farm_Key: "BLC016",
    Produce_Type: "pumpkin",
    season: "fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 313,
    ProduceDir: 316,
    Farm_Key: "BLC016",
    Produce_Type: "peas",
    season: "spring,fall",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 314,
    ProduceDir: 317,
    Farm_Key: "BLC016",
    Produce_Type: "summer squash",
    season: "summer",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 315,
    ProduceDir: 318,
    Farm_Key: "BLC016",
    Produce_Type: "radish",
    season: "spring,fall",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 316,
    ProduceDir: 319,
    Farm_Key: "BLC016",
    Produce_Type: "spinach",
    season: "spring,fall",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 317,
    ProduceDir: 320,
    Farm_Key: "BLC016",
    Produce_Type: "turnip",
    season: "spring,fall,winter",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
  {
    OID_: 318,
    ProduceDir: 321,
    Farm_Key: "BLC016",
    Produce_Type: "tomato",
    season: "summer",
    X: 0,
    Y: 0,
    Farm_Name: " ",
    Full_Addre: " ",
    Email: " ",
    Website: " ",
  },
];
